### ISSUE TITLE
tls-sni deprecation

### ISSUE THREAD

**Issue by bpennypacker** [cliffalbert/scripts#1]
certbot is deprecating tls-sni authentication, which is what your scripts currently rely on. See https://community.letsencrypt.org/t/upcoming-tls-sni-deprecation-in-certbot/76383 for details. Any plans to update your scripts to use one of the other authentication methods (tls-alpn-01,http-01,dns-01) instead?

**Comment by cliffalbert** [comment]
Changed over to http-01 for now, first tests indicates this works fine.
Just make sure you have no services listening on tcp/80.
